manifest:
  remotes:
    - name: nanopb
      url-base: https://github.com/nanopb
  projects:
    - name: nanopb
      revision: master
      path: modules_bridge/lib/nanopb
      
      import: west.yml