manifest:
  remotes:
    - name: nanopb
      url-base: https://github.com/nanopb
  project-imports:
    allow-override: true
  projects:
    - name: nanopb
      revision: master
      path: modules_bridge/lib/nanopb
      
      import: west.yml