name: Collect bridge proto files from modules

on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  collect-proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install libs
        run: |
          pip install west protobuf
          sudo apt install -y protobuf-compiler
      
      - name: Initialize West workspace
        run: |
          west init -l ./config
          west update
      
      - name: Collect proto files
        run: |
          mkdir -p collected-protos
          echo "Collecting proto files from modules..."

          for module_path in $(west list -f {path}); do
              if [ -d "$module_path/proto" -a "$module_path" != "modules/msgs/zmk-studio-messages" ]; then
                  echo "Found proto directory in: $module_path"
                  find "$module_path/proto" -name "*.proto" -type f | while read proto_file; do
                      cp "$proto_file" "collected-protos/"
                      echo "Collected: $proto_file -> collected-protos/$(basename "$proto_file")"
                  done
              fi
          done

      - name: Compile proto files
        run: |
          mkdir -p compiled-protos
          echo "Compiling proto files from modules..."

          protoc -I=collected-protos --python_out=compiled-protos collected-protos/*.proto

      - name: Remove bridge_pb2.py
        run: |
          rm compiled-protos/bridge_pb2.py

      - name: Rename proto files
        run: |
          for f in compiled-protos/*_pb2.py; do mv "$f" "${f%_pb2.py}.py"; done
      
      - name: Upload proto files artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-proto
          path: compiled-protos
          retention-days: 30